set(CPACK_PACKAGE_NAME "QO CLI")
set(CPACK_DEBIAN_PACKAGE_NAME "qo-cli")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "QO CLI")
set(CPACK_PACKAGE_VENDOR "Quantinuum")

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
SET(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_BINARY_DIR}/_packages")

if(UNIX)
    set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
else()
    set(CPACK_PACKAGING_INSTALL_PREFIX "/")
endif(UNIX)

set(CPACK_PACKAGE_VERSION_MAJOR ${QO_CLI_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${QO_CLI_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${QO_CLI_VERSION_PATCH})

set(CPACK_PACKAGE_CONTACT "quantumorigin@quantinuum.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Quantinuum <${CPACK_PACKAGE_CONTACT}>")

set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_STRIP_FILES YES)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)
set(CPACK_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE
    GROUP_READ GROUP_EXECUTE
    WORLD_READ WORLD_EXECUTE)
set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION TRUE)

if(WIN32)
    include (InstallRequiredSystemLibraries)
endif(WIN32)

include(CPack)
